apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  credentials: W3VkLWFkbWluXQphd3NfYWNjZXNzX2tleV9pZCA9IEFLSUFYRTU1VFpGQjRFUklDMk1NCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9IEdVOE5jVjdPaU9VRWJlRThQaW5sRCtVREpPT2VxaTdJS0YyYmRPT2c=