apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-configmap
data:
  credentials: |
    [ud-admin]
    aws_access_key_id = AKIAXE55TZFB4ERIC2MM
    aws_secret_access_key = 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
      