apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/adetle/udagram-api-user:v2
        envFrom:
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
          - configMapRef:
              name: env-configmap
        ports:
          - containerPort: 8080
        

---
apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend-user