apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: frontend
        image: docker.io/adetle/udagram-reverseproxy:v2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: reverseproxy